
// This file has been generated by the GUI designer. Do not modify.
namespace Screenary.Client
{
	public partial class JoinDialog
	{
		private global::Gtk.VBox dialog1_VBox1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label lblSessionKey;
		private global::Gtk.Entry txtSessionKey;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonJoin;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Screenary.Client.JoinDialog
			this.Name = "Screenary.Client.JoinDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Join a session");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Screenary.Client.JoinDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.dialog1_VBox1 = new global::Gtk.VBox ();
			this.dialog1_VBox1.Name = "dialog1_VBox1";
			this.dialog1_VBox1.Spacing = 6;
			this.dialog1_VBox1.BorderWidth = ((uint)(6));
			// Container child dialog1_VBox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblSessionKey = new global::Gtk.Label ();
			this.lblSessionKey.Name = "lblSessionKey";
			this.lblSessionKey.LabelProp = global::Mono.Unix.Catalog.GetString ("Session Key:");
			this.hbox1.Add (this.lblSessionKey);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.lblSessionKey]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(6));
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtSessionKey = new global::Gtk.Entry ();
			this.txtSessionKey.WidthRequest = 150;
			this.txtSessionKey.CanFocus = true;
			this.txtSessionKey.Name = "txtSessionKey";
			this.txtSessionKey.IsEditable = true;
			this.txtSessionKey.InvisibleChar = '•';
			this.hbox1.Add (this.txtSessionKey);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtSessionKey]));
			w3.Position = 1;
			w3.Padding = ((uint)(6));
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.dialog1_VBox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox1 [this.vbox3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(6));
			w1.Add (this.dialog1_VBox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.dialog1_VBox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Internal child Screenary.Client.JoinDialog.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonCancel]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonJoin = new global::Gtk.Button ();
			this.buttonJoin.CanDefault = true;
			this.buttonJoin.CanFocus = true;
			this.buttonJoin.Name = "buttonJoin";
			this.buttonJoin.UseUnderline = true;
			// Container child buttonJoin.Gtk.Container+ContainerChild
			global::Gtk.Alignment w9 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w10 = new global::Gtk.HBox ();
			w10.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-connect", global::Gtk.IconSize.Menu);
			w10.Add (w11);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w13 = new global::Gtk.Label ();
			w13.LabelProp = global::Mono.Unix.Catalog.GetString ("Join");
			w13.UseUnderline = true;
			w10.Add (w13);
			w9.Add (w10);
			this.buttonJoin.Add (w9);
			this.AddActionWidget (this.buttonJoin, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonJoin]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 526;
			this.DefaultHeight = 142;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonJoin.Clicked += new global::System.EventHandler (this.OnButtonJoinClicked);
		}
	}
}
