
// This file has been generated by the GUI designer. Do not modify.
namespace Screenary.Client
{
	public partial class IncomingRequestDialog
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label usernamelbl;
		private global::Gtk.Label infolbl;
		private global::Gtk.Button buttonDeny;
		private global::Gtk.Button buttonGrant;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Screenary.Client.IncomingRequestDialog
			this.Name = "Screenary.Client.IncomingRequestDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Incoming Request");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Screenary.Client.IncomingRequestDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(17));
			// Container child hbox1.Gtk.Box+BoxChild
			this.usernamelbl = new global::Gtk.Label ();
			this.usernamelbl.Name = "usernamelbl";
			this.usernamelbl.LabelProp = global::Mono.Unix.Catalog.GetString ("username");
			this.hbox1.Add (this.usernamelbl);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.usernamelbl]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.infolbl = new global::Gtk.Label ();
			this.infolbl.Name = "infolbl";
			this.infolbl.LabelProp = global::Mono.Unix.Catalog.GetString ("is requesting control");
			this.hbox1.Add (this.infolbl);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.infolbl]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child Screenary.Client.IncomingRequestDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonDeny = new global::Gtk.Button ();
			this.buttonDeny.CanDefault = true;
			this.buttonDeny.CanFocus = true;
			this.buttonDeny.Name = "buttonDeny";
			this.buttonDeny.UseUnderline = true;
			this.buttonDeny.Label = global::Mono.Unix.Catalog.GetString ("Deny");
			this.AddActionWidget (this.buttonDeny, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonDeny]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonGrant = new global::Gtk.Button ();
			this.buttonGrant.CanDefault = true;
			this.buttonGrant.CanFocus = true;
			this.buttonGrant.Name = "buttonGrant";
			this.buttonGrant.UseUnderline = true;
			this.buttonGrant.Label = global::Mono.Unix.Catalog.GetString ("Grant");
			this.AddActionWidget (this.buttonGrant, -3);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonGrant]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 145;
			this.Show ();
			this.buttonDeny.Clicked += new global::System.EventHandler (this.OnButtonDenyClicked);
			this.buttonGrant.Clicked += new global::System.EventHandler (this.OnButtonGrantClicked);
		}
	}
}
